# Declarative reusable workflow for mirroring branch create/delete
on:
  workflow_call:
    inputs:
      target_owner:
        required: true
        type: string
      target_repo:
        required: true
        type: string
      base_ref:
        required: true
        type: string
      skip_actor:
        required: false
        type: string
        default: github-actions[bot]
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Determine event and ref
        id: info
        run: |
          echo "EVENT=$GITHUB_EVENT_NAME"       >> $GITHUB_OUTPUT
          echo "ACTOR=$GITHUB_ACTOR"            >> $GITHUB_OUTPUT
          
          # For delete events, get the branch name from the event payload
          if [ "$GITHUB_EVENT_NAME" = "delete" ]; then
            BRANCH=$(jq -r '.ref' $GITHUB_EVENT_PATH | sed 's/refs\/heads\///')
          else
            BRANCH=$GITHUB_REF_NAME
          fi
          echo "BRANCH=$BRANCH"                 >> $GITHUB_OUTPUT

      - name: Skip if actor should be ignored
        if: ${{ inputs.skip_actor == steps.info.outputs.ACTOR }}
        run: |
          echo "Skipping mirror for actor ${{ steps.info.outputs.ACTOR }}"
          exit 0

      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ inputs.target_owner }}
          repositories: ${{ inputs.target_repo }}

      - name: Mirror branch creation
        if: ${{ steps.info.outputs.EVENT == 'create' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const branch = `${{ steps.info.outputs.BRANCH }}`;
            const target_owner = `${{ inputs.target_owner }}`;
            const target_repo = `${{ inputs.target_repo }}`;
            const base_ref = `${{ inputs.base_ref }}`;
            // Check existence
            try {
              await github.rest.git.getRef({ owner: target_owner, repo: target_repo, ref: `heads/${branch}` });
              console.log(`refs/heads/${branch} already exists, skipping`);
            } catch (err) {
              if (err.status === 404) {
                // Fetch base SHA
                const { data: base } = await github.rest.git.getRef({
                  owner: target_owner,
                  repo: target_repo,
                  ref: `heads/${base_ref}`
                });
                // Create new ref
                await github.rest.git.createRef({
                  owner: target_owner,
                  repo: target_repo,
                  ref: `refs/heads/${branch}`,
                  sha: base.object.sha
                });
                console.log(`Created refs/heads/${branch}`);
              } else {
                throw err;
              }
            }

      - name: Mirror branch deletion
        if: ${{ steps.info.outputs.EVENT == 'delete' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const branch = `${{ steps.info.outputs.BRANCH }}`;
            const target_owner = `${{ inputs.target_owner }}`;
            const target_repo = `${{ inputs.target_repo }}`;
            
            console.log(`Event: ${{ steps.info.outputs.EVENT }}`);
            console.log(`Branch to delete: "${branch}"`);
            console.log(`Target owner: ${target_owner}`);
            console.log(`Target repo: ${target_repo}`);
            
            // Skip if branch is empty, undefined, or main or production
            if (!branch || branch === 'main' || branch === 'production') {
              console.log(`Skipping deletion of branch "${branch}" - likely default branch or empty`);
              return;
            }
            
            // Skip delete if there are any open PRs for this branch
            const { data: prs } = await github.rest.pulls.list({
              owner: target_owner,
              repo: target_repo,
              head: `${target_owner}:${branch}`,
              state: 'open'
            });
            if (prs.length > 0) {
              console.log(`Branch ${branch} has open PR(s); skipping delete`);
              return;
            }
            // Proceed to delete if no open PRs
            try {
              await github.rest.git.deleteRef({
                owner: target_owner,
                repo: target_repo,
                ref: `heads/${branch}`
              });
              console.log(`Deleted refs/heads/${branch}`);
            } catch (err) {
              if (err.status === 404) {
                console.log(`refs/heads/${branch} not found, skipping delete`);
              } else {
                throw err;
              }
            }
